### ISSUE TITLE
Failed to lookup symbol (undefined symbol: sp_list_ports)

### ISSUE THREAD

**Issue by lauwen** [jpnurmi/dart_serial_port#5]
Invalid argument(s): Failed to lookup symbol (undefined symbol: sp_list_ports)
when try to use this lib in flutter android app?

**Comment by jpnurmi** [comment]
Can you try with [`flutter_serial_port`](https://github.com/jpnurmi/flutter_serial_port) in pubspec.yaml?

```yaml
dependencies:
  flutter_serial_port:
    git: git://github.com/jpnurmi/flutter_serial_port.git
```

It will automatically build and deploy `libserialport.so` as appropriate.

P.S. I'm not sure what kind of hardware you have, but on Android, you're also likely face issues with permissions. There's some ongoing discussion and tips at: https://github.com/jpnurmi/dart_serial_port/issues/3
